image: node:20

before_script:
  - cd StudyChain

build-job:
  stage: build
  script:
    - npm install
    - find -name "*.js" | xargs node -c

deploy-heroku:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
