image: node:16

stages:
  - build

cache:
  paths:
    - node_modules/

before_script:
  - echo "Checking out the repository"
  - git checkout $CI_COMMIT_REF_NAME

build_job:
  stage: build
  script:
    - echo "Installing dependencies"
    - npm install
    - echo "Building the project"
    - npm run build
